In [1]:
import pandas as pd

In [2]:
%%time
merge_df = pd.read_csv('../data/raw/log_problem.csv')

Wall time: 40 s

In [6]:
merge_df.columns

Index(['timestamp_TW', 'uuid', 'ucid', 'upid', 'problem_number',
       'exercise_problem_repeat_session', 'is_correct', 'total_sec_taken',
       'total_attempt_cnt', 'used_hint_cnt', 'is_hint_used', 'is_downgrade',
       'is_upgrade', 'level'],
      dtype='object')

In [8]:
merge_df['timestamp_TW'] = pd.to_datetime(merge_df['timestamp_TW'], format='%Y-%m-%d %H:%M:%S %Z')
merge_df = merge_df.rename(columns = {'timestamp_TW':'datetime_attempt'})

In [9]:
merge_df['datetime_attempt'].describe()

count                      16217311
unique                        30507
top       2019-03-19 16:30:00+00:00
freq                           7660
first     2018-08-01 07:45:00+00:00
last      2019-08-01 00:00:00+00:00
Name: datetime_attempt, dtype: object

In [16]:
merge_df.sort_values('datetime_attempt')

,datetime_attempt,uuid,ucid,upid,problem_number,exercise_problem_repeat_session,is_correct,total_sec_taken,total_attempt_cnt,used_hint_cnt,is_hint_used,is_downgrade,is_upgrade,level
105021,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,CPI+5YCeEmhqdk6znJeii6jJUNl1QWGEvwCUJ6uLflg=,9Ksy3bdm0HTi0D+cdKSBKDQJjo5GNahep91FqHUrpts=,2,1,True,8,1,0,False,NaN,NaN,0
11669798,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,CPI+5YCeEmhqdk6znJeii6jJUNl1QWGEvwCUJ6uLflg=,/Wgjdl2BsldHZDdXXvzwGimusaMX548lqV2b7PgwXAs=,1,1,True,10,1,0,False,NaN,NaN,0
3768239,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,CPI+5YCeEmhqdk6znJeii6jJUNl1QWGEvwCUJ6uLflg=,vsGlLPd9C58B8myBoGMGre2pDHjh62eRjsqX57D98fU=,5,1,True,6,1,0,False,False,True,1
10163558,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,hv7kHCAIdj7thZUmlqz553leG5bFNYgzXmLfB5m4Xvw=,h3CI/U4QJd6mjYE5xRH8QEst8lRG7otYIz+q1V6Och4=,5,1,True,5,1,0,False,False,True,1
8372688,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,CPI+5YCeEmhqdk6znJeii6jJUNl1QWGEvwCUJ6uLflg=,OSuDd4rDo2muXXwwJRU2DQVHkk6/JOGgNzfzNi4PMJM=,3,1,True,4,1,0,False,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5351619,2019-08-01 00:00:00+00:00,liamj78o0Ae2wnaS0hq7LUfSTsp3xB6HEcffaKBUzGc=,lG8uYsrQADh32pvOcrvytT25qo4UpZUGkrybb4ycFEs=,6yQTtifKhIRKCTcjWwYgZEJgiJeKvNzlI9b5pRh5d4s=,6,1,True,18,1,0,False,False,True,1
8225534,2019-08-01 00:00:00+00:00,DndeYzUnQn5RMFK82bE5EUK7UeWFnO3VgT7uAuluqTM=,Av3E5D+JWfyHjDr2vSsiW200MsgBmim5sLZc4UBQM/0=,/ehY6iTAB3z7NB52RLi87aynoVLADwEjle/pIW6WHig=,9,1,True,7,1,0,False,NaN,NaN,1
14727695,2019-08-01 00:00:00+00:00,t2N6muKWIarXYsUVv/M4rOx/+Qe0Gy9eC0ufuf7vZ0c=,GcuG2ukgxXmym9WSnWnlpKVNUFysZ8QfpAgpJMcheMU=,HEFfwmy7pwKhEadwn+17iN+Ik+TEWh7KE6fbKWuf0RU=,6,1,False,102,2,0,False,NaN,NaN,1
13201613,2019-08-01 00:00:00+00:00,hCyJTrhgUprNNWpJYKPcyHIxDHnbW91tv0OEM0wXSuI=,Wk1PobqnhB1FsjjiU84gVNe9j4O6SLWWYfvGb/l6MR4=,o1ITX1QcpkBe8d4UjsZH3yUfBC9caKoPTJV7Ls6IqNE=,5,1,True,5,1,0,False,False,True,1
15112240,2019-08-01 00:00:00+00:00,liamj78o0Ae2wnaS0hq7LUfSTsp3xB6HEcffaKBUzGc=,zcH7Yl/gFwkU2Mej9UzQgaJL66wIdiMucPZwVyeqHxc=,Ms5i+EI/9bpS14wA2YcLHjmfReyVKqfjXuXJe2o9ds8=,1,1,True,31,1,0,False,NaN,NaN,0

In [17]:
merge_df.sort_values('datetime_attempt', ascending=False)

,datetime_attempt,uuid,ucid,upid,problem_number,exercise_problem_repeat_session,is_correct,total_sec_taken,total_attempt_cnt,used_hint_cnt,is_hint_used,is_downgrade,is_upgrade,level
261862,2019-08-01 00:00:00+00:00,liamj78o0Ae2wnaS0hq7LUfSTsp3xB6HEcffaKBUzGc=,LpZS/GFsDGjF3rEt7YLZd8IYdScjZ5Z+5bJuJ/c2BZs=,eaAEkSxQp9angg4kDy3ficPYd0bfdDxS4q9sjK2Fo14=,5,1,True,12,1,0,False,False,True,1
369192,2019-08-01 00:00:00+00:00,liamj78o0Ae2wnaS0hq7LUfSTsp3xB6HEcffaKBUzGc=,zcH7Yl/gFwkU2Mej9UzQgaJL66wIdiMucPZwVyeqHxc=,Fw4p8lJQI2zOjEq+Ks0tYVk39iauEqSDH4HSZQWUqX8=,2,1,True,26,1,0,False,NaN,NaN,0
13403866,2019-08-01 00:00:00+00:00,hCyJTrhgUprNNWpJYKPcyHIxDHnbW91tv0OEM0wXSuI=,pHm5o9NLjlO2lXB7CH2U80qF20rcHwHgxaIwnQiSd/c=,RBwSFeQxeHRHylsP/Or/i8D0LOhWtC9lWa34qJjyXMA=,5,1,True,10,1,0,False,False,True,1
367795,2019-08-01 00:00:00+00:00,hCyJTrhgUprNNWpJYKPcyHIxDHnbW91tv0OEM0wXSuI=,Iri0Mm69Jhy9dYumaZScJt7B6cHJhAjve5Ii96kP4vc=,ZyOMpsMQKJBz6scnEpYrPCf3COQAr6q8d5+hPk5QUAY=,39,4,True,17,1,0,False,NaN,NaN,1
13180283,2019-08-01 00:00:00+00:00,hCyJTrhgUprNNWpJYKPcyHIxDHnbW91tv0OEM0wXSuI=,pHm5o9NLjlO2lXB7CH2U80qF20rcHwHgxaIwnQiSd/c=,k4RP6kLahU5tlMn/51BHtygZ12E3FKdeWSk/+rxoNtc=,4,1,True,35,1,0,False,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13311409,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,CPI+5YCeEmhqdk6znJeii6jJUNl1QWGEvwCUJ6uLflg=,OE6ac/KSBYPUdQIN5KjVZS1QSxWiKqis6mIYB0s6kV4=,4,1,True,7,1,0,False,NaN,NaN,0
3768239,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,CPI+5YCeEmhqdk6znJeii6jJUNl1QWGEvwCUJ6uLflg=,vsGlLPd9C58B8myBoGMGre2pDHjh62eRjsqX57D98fU=,5,1,True,6,1,0,False,False,True,1
10163558,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,hv7kHCAIdj7thZUmlqz553leG5bFNYgzXmLfB5m4Xvw=,h3CI/U4QJd6mjYE5xRH8QEst8lRG7otYIz+q1V6Och4=,5,1,True,5,1,0,False,False,True,1
11669798,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,CPI+5YCeEmhqdk6znJeii6jJUNl1QWGEvwCUJ6uLflg=,/Wgjdl2BsldHZDdXXvzwGimusaMX548lqV2b7PgwXAs=,1,1,True,10,1,0,False,NaN,NaN,0
2146461,2018-08-01 07:45:00+00:00,U+lqK/FKWkPuoNUM1AbGyrKZfXeQrRRoKOToKrjqDt4=,hv7kHCAIdj7thZUmlqz553leG5bFNYgzXmLfB5m4Xvw=,hYmhOfMMKaQNTrGze5TdATN0HNGJUEjDIYQaocuD4QY=,2,1,True,6,1,0,False,NaN,NaN,0